name: geohex
description: Dart implementation of Hexagonal geo-coding system (GeoHex.org) encoding.
version: 3.2.0+7
homepage: https://github.com/NiKoTron/geohex

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
