name: geohex
description: Dart implementation of Hexagonal geo-coding system (GeoHex.org) encoding.
version: 3.2.0+6
homepage: https://github.com/NiKoTron/geohex

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
