name: geohex
description: Dart implementation of Hexagonal geo-coding system (GeoHex.org) encoding.
version: 3.2.0+4
homepage: https://github.com/NiKoTron/geohex
author: Nikolai Simonov <nickolay.simonov@outlook.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.5
