name: geohex
description: Dart implementation of GeoHex encoding.
version: 3.2.0+1
homepage: https://github.com/NiKoTron/geohex
author: Nikolai Simonov <nickolay.simonov@outlook.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
